name: daml-script
id: daml-script-3.4.11
version: 3.4.11
exposed: True
exposed-modules: Daml.Script.Internal.Questions.Crypto.Text Daml.Script Daml.Script.Internal.Questions.Crypto Daml.Script.Internal.Questions.Query Daml.Script.Internal.Questions.Submit.Error Daml.Script.Internal.Questions.PartyManagement Daml.Script.Internal.Questions.TransactionTree Daml.Script.Internal.Questions Daml.Script.Internal.Questions.Commands Daml.Script.Internal.LowLevel Daml.Script.Internal.Questions.Time Daml.Script.Internal.Questions.Util Daml.Script.Internal Daml.Script.Internal.Questions.Testing Daml.Script.Internal.Questions.Exceptions Daml.Script.Internal.Questions.Packages Daml.Script.Internal.Questions.Submit Daml.Script.Internal.Free Daml.Script.Internal.Questions.UserManagement
import-dirs: ${pkgroot}/daml-script-3.4.11-32d940b3c927ec6cf02efe503f901d4109cb9c59c1f17f16a64db8adfe108f6d
library-dirs: ${pkgroot}/daml-script-3.4.11-32d940b3c927ec6cf02efe503f901d4109cb9c59c1f17f16a64db8adfe108f6d
data-dir: ${pkgroot}/daml-script-3.4.11-32d940b3c927ec6cf02efe503f901d4109cb9c59c1f17f16a64db8adfe108f6d
depends: daml-prim daml-stdlib-3.4.11
